# global options
dist: xenial
language:
  - c
compiler:
  - gcc
cache:
  directories:
    - "${HOME}/persist"
env:
  global:
    - MAKEOPTS="-j4"
git:
  core.symlinks: false

# define the successive stages
stages:
  - name: test

# define the jobs for the stages
# order of the jobs has longest running first to optimise total time
jobs:
  include:
    # rx port
    - stage: test
      env: NAME="rx port build"
      install:
        - sudo apt-get update -qq || true
        - sudo apt-get install -y libc6:i386 libncurses5:i386 libstdc++6:i386
        - sudo apt-get install -y bzip2
        - sudo apt-get install -y wget
        - sudo apt-get install -y build-essential        
        - sudo apt-get install -y python3
        - wget "https://ksgadget.blob.core.windows.net/test/rx-elf-gcc-4.9.4.tar.gz" -k -O rx-elf-gcc-4.9.4.tar.gz
        - tar xvf rx-elf-gcc-4.9.4.tar.gz
        - sudo mv ./rx-elf-gcc-4.9.4 /opt
        - sudo chmod 777 /opt/rx-elf-gcc-4.9.4
        - export PATH=/opt/opt/rx-elf-gcc-4.9.4/bin:$PATH
      script:
        - make ${MAKEOPTS} -C mpy-cross
        - make ${MAKEOPTS} -C ports/rx V=1 DEBUG=1 MICROPY_PY_ESP8266=1 MICROPY_SSL_MBEDTLS=1 MICROPY_PY_USSL=1 BOARD=GR_CITRUS

